---
# Download arkmanager init script
- name: Download arkmanager from git repo
  get_url:
    url: https://raw.githubusercontent.com/arkmanager/ark-server-tools/master/netinstall.sh
    dest: /tmp/install.sh
    mode: 0777

# Check if arkmanager cmd is installed
- name: Check if arkmanager is installed
  command: which arkmanager
  register: arkmanager_installed
  changed_when: false
  ignore_errors: yes

# Check arkmanager version
- name: Check arkmanager version and status
  command: arkmanager --version
  register: arkmanager_version
  changed_when: false
  ignore_errors: yes

# Install arkmanager cmd
- name: Run the arkmanager install script
  shell: cat /tmp/install.sh | sudo bash -s ark
  when: "arkmanager_installed.stdout == ''"

# Run the arkmanager installer
- name: Run arkmanager installer
  command: arkmanager install
  when: "arkmanager_version.stderr.find('ERROR') != -1"
